edition = "2024"
merge_derives = false
newline_style = "Unix"
reorder_imports = true
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Max"

# unstable features
#control_brace_style = "ClosingNextLine"
#struct_field_align_threshold = 20