edition                        = "2024"

array_width                    = 100
attr_fn_like_width             = 100
chain_width                    = 100
fn_call_width                  = 100
hard_tabs                      = false
match_arm_leading_pipes        = "Preserve"
match_block_trailing_comma     = true
max_width                      = 120
merge_derives                  = false
newline_style                  = "Unix"
reorder_imports                = true
single_line_if_else_max_width  = 100
single_line_let_else_max_width = 100
tab_spaces                     = 2
use_field_init_shorthand       = true
use_small_heuristics           = "Max"

# unstable features
#control_brace_style = "ClosingNextLine"
#struct_field_align_threshold = 20