name: Release
run-name: ${{ github.actor }} is publishing release ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  FORCE_COLOR: "1"
  TAR_FILE: "river-status-${{ github.ref_name }}.tgz"
  TAR_CHECKSUM_FILE: "river-status-${{ github.ref_name }}.tgz.sha256"
  ZIP_FILE: "river-status-${{ github.ref_name }}.zip"
  ZIP_CHECKSUM_FILE: "river-status-${{ github.ref_name }}.zip.sha256"

# inputs:
#   github_token:
#     description: "GitHub token for authentication"
#     required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: true

      # Install Rust toolchain
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Run Clippy (linting)
      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings

      # Check code formatting
      - name: Check formatting
        run: cargo fmt --all --check

  release:
    permissions:
      contents: write
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: create the archives
        run: |
          # git clone --no-checkout --filter=blob:none  https://github.com/riverwm/river.git river
          # git submodule add https://github.com/riverwm/river.git river
          git submodule absorbgitdirs
          git -C river config core.sparseCheckout true
          echo '/protocol/' >>.git/modules/river/info/sparse-checkout
          git submodule update --init --force --checkout river
          mkdir -p archive
          tar --exclude="archive" --exclude=".git" --exclude=".github" -czvf archive/${TAR_FILE} .
          zip -r archive/${ZIP_FILE} . -x "archive/*" -x ".git/*" -x ".github/*"
          mv archive/* .

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   env:
      #     GITHUB_TOKEN: ${{ inputs.github-token }}
      #   with:
      #     tag_name: ${{ env.RELEASE_VERSION }}
      #     name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false

      - name: generate tar.gz checksums
        run: |
          CONTENT=$( sha256sum ${TAR_FILE} )
          SHA256=$( printf "%s %s" ${CONTENT} | cut -d ' ' -f1 )
          [[ ! ${SHA256} =~ ^[a-z0-9]+$ ]] && printf "%s\n%s, could not calculate sha256\n" "${CONTENT}" "${SHA256}" && exit 1
          printf "%s %s" ${CONTENT} > "${TAR_CHECKSUM_FILE}"
      - name: generate zip checksums
        run: |
          CONTENT=$( sha256sum ${ZIP_FILE} )
          SHA256=$( printf "%s %s" ${CONTENT} | cut -d ' ' -f1 )
          [[ ! ${SHA256} =~ ^[a-z0-9]+$ ]] && printf "%s\n%s, could not calculate sha256\n" "${CONTENT}" "${SHA256}" && exit 1
          printf "%s %s" ${CONTENT} > "${ZIP_CHECKSUM_FILE}"

      - name: write checksum
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          files: |
            ${{ github.workspace }}/*.sha256
            ${{ github.workspace }}/*.tgz
            ${{ github.workspace }}/*.zip
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
