name: Release
run-name: ${{ github.actor }} is publishing release ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  FORCE_COLOR: "1"

# inputs:
#   github_token:
#     description: "GitHub token for authentication"
#     required: true

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  checksums:
    name: sha256
    permissions:
      contents: write
    needs:
      - build
    runs-on: ubuntu-latest
    env:
      CHECKSUM_FILE: ${{ github.ref_name }}.tar.gz.sha256
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Tarball url
        run: echo "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz"
      - name: Create tarball sha256
        working-directory: ${{ github.workspace }}
        run: |
          gh release download ${{ github.ref_name }} --archive=tar.gz --output release.tgz
          SHA256=$( sha256sum ./release.tgz | cut -d ' ' -f1 )
          [[ ! ${SHA256} =~ ^[a-z0-9]+$ ]] && printf "could not calculate sha256\n" && exit 1
          printf "%s" ${SHA256} > "${CHECKSUM_FILE}"
      - name: write checksum
        uses: softprops/action-gh-release@v2
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ github.workspace }}/${CHECKSUM_FILE}
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
