name: Release
run-name: ${{ github.actor }} is publishing release ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  FORCE_COLOR: "1"
  TAR_FILE: "river-status-${{ github.ref_name }}.tgz"
  TAR_CHECKSUM_FILE: "river-status-${{ github.ref_name }}.tgz.sha256"
  ZIP_FILE: "river-status-${{ github.ref_name }}.zip"
  ZIP_CHECKSUM_FILE: "river-status-${{ github.ref_name }}.zip.sha256"

# inputs:
#   github_token:
#     description: "GitHub token for authentication"
#     required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: true

      # Install Rust toolchain
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Run Clippy (linting)
      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings

      # Check code formatting
      - name: Check formatting
        run: cargo fmt --all --check

  release:
    permissions:
      contents: write
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: true

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Git-archive-all
        uses: qmonnet/git-archive-all-action@v1.0.1
        with:
          force-submodules: true
          output-files: ${TAR_FILE} ${ZIP_FILE}

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   env:
      #     GITHUB_TOKEN: ${{ inputs.github-token }}
      #   with:
      #     tag_name: ${{ env.RELEASE_VERSION }}
      #     name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false

      - name: generate tar.gz checksums
        run: |
          # gh release download ${{ github.ref_name }} --archive=tar.gz --output ${{ github.ref_name }}.tgz
          CONTENT=$( sha256sum ${TAR_FILE} )
          SHA256=$( printf "%s %s" ${CONTENT} | cut -d ' ' -f1 )
          [[ ! ${SHA256} =~ ^[a-z0-9]+$ ]] && printf "%s\n%s, could not calculate sha256\n" "${CONTENT}" "${SHA256}" && exit 1
          printf "%s %s" ${CONTENT} > "${TAR_CHECKSUM_FILE}"
      - name: generate zip checksums
        run: |
          CONTENT=$( sha256sum ${ZIP_FILE} )
          SHA256=$( printf "%s %s" ${CONTENT} | cut -d ' ' -f1 )
          [[ ! ${SHA256} =~ ^[a-z0-9]+$ ]] && printf "%s\n%s, could not calculate sha256\n" "${CONTENT}" "${SHA256}" && exit 1
          printf "%s %s" ${CONTENT} > "${ZIP_CHECKSUM_FILE}"

      - name: write checksum
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          files: |
            ${{ github.workspace }}/*.sha256
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
